  </div>
  <div class="col-md-6">
  <!-- tmpl_if name="logo" --><img src="<!-- tmpl_var name="logo" -->" class="img-responsive img-thumbnail center-block" style="margin-bottom:20px"/><!-- /tmpl_if -->
  <div class="text-center">
  <!-- tmpl_if name="soundcloud" --><a href="<!-- tmpl_var name="soundcloud" -->" title="Écouter sur SoundCloud" class="btn btn-default"><i class="fa fa-soundcloud"></i></a><!-- /tmpl_if -->
  <!-- tmpl_if name="jamendo" --><a href="<!-- tmpl_var name="jamendo" -->" title="Écouter sur Jamendo" class="btn btn-default"><i class="fa fa-music"></i></a><!-- /tmpl_if -->
  <!-- tmpl_if name="dogmazic" --><a href="<!-- tmpl_var name="dogmazic" -->" title="Écouter sur Dogmazic" class="btn btn-default"><i class="fa fa-headphones"></i></a><!-- /tmpl_if -->
  <!-- tmpl_if name="youtube" --><a href="<!-- tmpl_var name="youtube" -->" title="Écouter sur Youtube" class="btn btn-default"><i class="fa fa-youtube"></i></a><!-- /tmpl_if -->
  </div>
  </div>
</div>
