    <!-- ##### Breadcumb Area Start ##### -->
    <section class="breadcumb-area bg-img bg-overlay" style="background-image: url(images/background2.jpg);">
        <div class="bradcumbContent">
            <h2><!-- tmpl_var name="title" --></h1>
        </div>
    </section>
    <!-- ##### Breadcumb Area End ##### -->

    <section class="section-padding-100-0 mb-70 mt-30 bg-img bg-fixed" style="background-image: url(images/guitar_white.png);">
        <div class="container">
            <div class="row">
                <div class="col-12 col-md-6">
