    <div class="navbar-wrapper">

        <div class="navbar navbar-default navbar-static-top" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="index.html"><i class="fa fa-hand-peace-o hidden-xs"></i><span class="visible-xs">Accueil</span></a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="bio.html"><i class="fa fa-user-circle-o"></i> Biographie</a></li>
                <li><a href="agenda.html"><i class="fa fa-calendar"></i> Agenda / Concerts</a></li>
                <li><a href="chansons.html"><i class="fa fa-music"></i> Chansons</a></li>
		<li class="dropdown">
		  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-share-alt-square"></i> Partager <span class="caret"></span></a>
		  <ul class="dropdown-menu" role="menu">
		    <li class="dropdown-header">Plates-formes musicales</li>
                    <li><a href="https://soundcloud.com/k_p_t_n" title="SoundCloud"><span class="fa-stack"><i class="fa fa-square fa-stack-2x"></i><i class="fa fa-soundcloud fa-stack-1x fa-inverse"></i></span> SoundCloud</a></li>
                    <li><a href="https://www.jamendo.com/artist/463782/kptn" title="Jamendo"><span class="fa-stack"><i class="fa fa-square fa-stack-2x"></i><i class="fa fa-music fa-stack-1x fa-inverse"></i></span> Jamendo</a></li>
                    <li><a href="http://play.dogmazic.net/browse.php?action=artist#artists.php?action=show&artist=6703" title="Dogmazic"><span class="fa-stack"><i class="fa fa-square fa-stack-2x"></i><i class="fa fa-dogmazic fa-stack-1x fa-inverse"></i></span> Dogmazic</a></li>
		    <li class="dropdown-header">Plates-formes vidéo</li>
                    <li><a href="https://www.youtube.com/playlist?list=PL6Ylmd_bS5AulDzi60aVK2fHLD_eoPqtu" title="YouTube"><span class="fa-stack"><i class="fa fa-square fa-stack-2x"></i><i class="fa fa-youtube fa-stack-1x fa-inverse"></i></span> YouTube</a></li>
		    <li class="dropdown-header">Réseaux sociaux</li>
                    <li><a rel="me" href="https://framapiaf.org/@kptnfrance" title="Mastodon"><span class="fa-stack"><i class="fa fa-square fa-stack-2x"></i><i class="fa fa-mastodon fa-stack-1x fa-inverse"></i></span> Mastodon</a></li>
                    <li><a href="https://www.facebook.com/kptnfrance/" title="Facebook"><span class="fa-stack"><i class="fa fa-square fa-stack-2x"></i><i class="fa fa-facebook fa-stack-1x fa-inverse"></i></span> Facebook</a></li>
                    <li><a href="https://www.twitter.com/kptnfrance/" title="Twitter"><span class="fa-stack"><i class="fa fa-square fa-stack-2x"></i><i class="fa fa-twitter fa-stack-1x fa-inverse"></i></span> Twitter</a></li>
		    <li class="dropdown-header">Autres</li>
                      <li><a href="https://framalibre.org/content/kptn" title="Framalibre"><span class="fa-stack"><i class="fa fa-square fa-stack-2x"></i><i class="fa fa-book fa-stack-1x fa-inverse"></i></span> Framalibre</a></li>
                      <li><a href="https://musicbrainz.org/artist/0ac3884e-99f0-4022-8f21-6c76e2f78486" title="MusicBrainz"><span class="fa-stack"><i class="fa fa-square fa-stack-2x"></i><i class="fa fa-star fa-stack-1x fa-inverse"></i></span> MusicBrainz</a></li>
		  </ul>
		</li>
		<li class="dropdown">
		  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-money"></i> Soutenir <span class="caret"></span></a>
		  <ul class="dropdown-menu" role="menu">
                    <li><a href="https://fr.tipeee.com/kptn" title="Tipee"><span class="fa-stack"><i class="fa fa-square fa-stack-2x"></i><i class="fa fa-tipeee fa-stack-1x fa-inverse"></i></span> Tipee</a></li>
                    <li><a href="https://liberapay.com/KPTN/" title="Liberapay"><span class="fa-stack"><i class="fa fa-square fa-stack-2x"></i><i class="fa fa-liberapay fa-stack-1x fa-inverse"></i></span> Liberapay</a></li>
		  </ul>
		</li>
              </ul>
            </div>
          </div>
        </div>

    </div>
