    <div class="navbar-wrapper">

        <div class="navbar navbar-default navbar-static-top" role="navigation">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="index.html"><i class="fa fa-hand-peace-o hidden-xs"></i><span class="visible-xs">Accueil</span></a>
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li><a href="bio.html"><i class="fa fa-user-circle-o"></i> Biographie</a></li>
                <li><a href="chansons.html"><i class="fa fa-music"></i> Chansons</a></li>
              </ul>
            </div>
          </div>
        </div>

    </div>
