
<div class="container">
  <div class="row section-padding-100-0 mb-70">
    <div class="col-md-4">
    </div> 
    <div class="col-md-4 text-center">
        <p><a href="/album-coeurk.html">CœurK</a></p>
        <a href="/album-coeurk.html"><img src="/images/workinprogress_320px.jpg" style="max-height: 160px;"/></a>
        <p><a href="/album-coeurk.html">Retour à la liste des chansons</a></p>
    </div> 
    <div class="col-md-4">
    </div> 
  </div>
</div>
