
<div class="container">
  <div class="row section-padding-100-0 mb-70">
    <div class="col-md-4">
    </div> 
    <div class="col-md-4 text-center">
        <p><a href="/album-flammes.html">Flammes</a></p>
        <a href="/album-flammes.html"><img src="/images/kptn_flammes_cover_320px.png" style="max-height: 160px;"/></a>
        <p><a href="/album-flammes.html">Retour à la liste des chansons</a></p>
    </div> 
    <div class="col-md-4">
    </div> 
  </div>
</div>
